services:
  - type: web
    name: backend
    env: node
    rootDir: ./backend
    buildCommand: npm run-script dev
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3001
      - key: HOST
        value: 0.0.0.0
      - key: DATABASE_URL
        fromDatabase:
          name: neondb
          property: connectionString
